name: wallet_core
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  fixnum: ^1.0.0
  protobuf: ^2.0.1
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.byneapp.wallet_core
        pluginClass: WalletCorePlugin
      ios:
        pluginClass: WalletCorePlugin

ffigen:
  name: TrustWallet
  description: Bindings to `HDWallet.h`.
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - '../include/TrustWalletCore/**.h'